#!/usr/bin/python
# ------------------------------------------------------------------------------------
#   WRW 19 Mar 2022 - Make a birdland.desktop file and 
#   customized to the type of packaging and installation location.
#   Install in ~/.local/share/applications where the menu software will find it.

#   Refresh KDE so it sees the file.
#       kbuildsycoca5 --noincremental

# ------------------------------------------------------------------------------------

import os
import sys
from pathlib import Path
import datetime
# import site
from Store import Store

# ------------------------------------------------------------------------------------

desktop_proto = """
# -----------------------------------------------------------------
#   birdland.desktop
#   Birdland Musician's Assistant             
#   This is generated by fb_make_desktop.py for a package type.
#   Generated: <Date>
#   Package type: <Type>
# -----------------------------------------------------------------

[Desktop Entry]
Categories=Audio;Player;AudioVideo;Midi;Viewer;
Comment[en_US]=
Comment=
Exec=<Exec>
Icon=<Icon>
Path=<Path>
GenericName[en_US]=Birdland Musician's Assistant
GenericName=Birdland Musician's Assistant
MimeType=
Name[en_US]=Birdland_Qt
Name=Birdland_Qt
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-Desktop-File-Install-Version=0.15
X-KDE-SubstituteUID=false
X-KDE-Username=
"""

# ------------------------------------------------------------------------------------

def make_desktop():

    s = Store()

    # -------------------------------------------------------
    #   Collect some common values.

    date = datetime.datetime.today().strftime( '%a, %d-%b-%Y, %H:%M:%S')
    home = os.getenv( 'HOME' )              # or os.environ[ 'HOME' ]

    # -------------------------------------------------------
    #   Get values specific to package_type

    #   Tar mimics Setuptools installation.

    package_type = s.Const.Package_Type 

    if package_type ==  'PyInstaller':
        executable = str( Path( sys.executable ).resolve())
        executable_parent = str( Path( sys.executable ).parent.resolve())
        Exec = f"/bin/sh -c {executable}"
        Icon = str(Path( s.Const.stdConfig, s.Const.Icon_File_PNG ))
        PPath = executable_parent

    elif package_type == 'Development':
        program = str( Path( sys.argv[0] ).resolve())           # Where birdland executed
        program_dir = str( Path( __file__ ).parent.resolve())   # Where modules live
        Exec = f"/bin/sh -c {program}"
        Icon = str(Path( s.Const.stdConfig, s.Const.Icon_File_PNG ))
        PPath = program_dir

    else:
        s.msgCritical( f"ERROR-DEV: Unexpected package_type '{package_type }' at make_desktop()" )
        sys.exit(1)

    # if package_type == 'Installed':
    #     program = str( Path( sys.argv[0] ).resolve() )          # Where birdland executed
    #     program_dir = str( Path( __file__ ).parent.resolve())  # Where modules live
    #     Exec = f"/bin/sh -c {program}"
    #     Icon = f"{program_dir}/Icons/Saxophone_64.png"
    #     PPath = program_dir

    # elif package_type == 'Unpacked':
    #     program = str( Path( sys.argv[0] ).resolve())          # Where birdland executed
    #     program_dir = str( Path( __file__ ).parent.resolve())  # Where modules live
    #     Exec = f"/bin/sh -c {program}"
    #     Icon = f"{program_dir}/Icons/Saxophone_64.png"
    #     PPath = program_dir

    # if package_type == 'Tar' or package_type == 'Setuptools' or package_type == 'GitHub':
    #     program = Path( sys.argv[0] ).resolve().as_posix()          # Where birdland executed
    #     program_dir = Path( __file__ ).parent.resolve().as_posix()  # Where modules live
    #     Exec = f"/bin/sh -c {program}"
    #     Icon = f"{program_dir}/Icons/Bluebird-64.png"
    #     PPath = program_dir

    # elif package_type  ==  'Nuitka':
    #     executable = Path( sys.executable ).resolve().as_posix()
    #     executable_parent = Path( sys.executable ).parent.resolve().as_posix()
    #     Exec = f"/bin/sh -c {executable_parent}/birdland"
    #     Icon = f"{executable_parent}/Icons/Bluebird-64.png"
    #     PPath = executable_parent

    #   This should be last as always present in install directory in addition to one of the above.
    #   Same as Tar, etc., above.

    # -------------------------------------------------------
    #   Do tilda expansion

    Exec = Exec.replace( '~', home )
    Icon = Icon.replace( '~', home )
    PPath = PPath.replace( '~', home )

    #   Substitute values in prototype

    d = desktop_proto
    d = d.replace( '<Exec>', Exec )
    d = d.replace( '<Icon>', Icon )
    d = d.replace( '<Path>', PPath )
    d = d.replace( '<Type>', package_type )
    d = d.replace( '<Date>', date )
    # d = d.replace( '<Python>', python )

    # -------------------------------------------------------
    #   Show off our work. No, only for debugging

    # if verbose:
    #     print( d )

    # -------------------------------------------------------
    #   Install the file for now on every launch. Important
    #   for testing because I will forget to remove it.

    opath = Path( s.Const.stdApplication, s.Const.BL_Desktop ).expanduser()
    # print( f"Writing to {opath}" )

    # if opath.is_file():
    #     print( f"NOTE: {opath} exists, overwriting", file=sys.stderr )

    opath.write_text( d )

# ------------------------------------------------------------------------------------

if __name__ == '__main__':
    make_desktop()
    if False:
        make_desktop( 'Development', True )
        make_desktop( 'Tar', True )
        make_desktop( 'Setuptools', True )
        make_desktop( 'PyInstaller', True )
        make_desktop( 'Nuitka', True )

# ------------------------------------------------------------------------------------
